name: TreexCastle
version: ${project.version}
main: org.jetby.treexcastle.TreexCastle
api-version: '1.20'
load: POSTWORLD
authors: [ MrJetby ]
website: https://dsc.gg/treexstudio
depend:
  - Libb
  - DecentHolograms
softdepend:
  - PlaceholderAPI
commands:
  shulker: {}